version: 2

build:
  os: 'ubuntu-20.04'
  tools:
    python: 'mambaforge-4.10'

conda:
  environment: quickBayes-dev-linux.yml


python:
  install:
  - requirements: docs/requirements.txt

sphinx:
  fail_on_warning: true

formats:
  - pdf
