version: 2

build:
  os: 'ubuntu-20.04'
  tools:
    python: 'mambaforge-4.10'

conda:
  environment: quickBayes-dev.yml


python:
  install:
    - method: pip
      path: .


sphinx:
  fail_on_warning: true

formats:
  - pdf
