# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
version: 2

build:
  os: 'ubuntu-20.04'
  tools:
    python: 'mambaforge-22.9'

conda:
  environment: quickBayes-dev.yml


python:
  install:
    - method: pip
      path: .


sphinx:
  fail_on_warning: true

formats:
  - pdf
