# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
version: 2

build:
  os: 'ubuntu-20.04'
  tools:
    python: 'mambaforge-22.9'
  jobs:
    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx docs/"


conda:
  environment: quickBayes-dev.yml


python:
  install:
    - method: pip
      path: .


sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
