# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
version: 2

build:
  os: 'ubuntu-20.04'
  tools:
    python: '3.11' #'mambaforge-4.10'
    use_system_site_packages: true

conda:
  environment: quickBayes-dev-linux.yml


python:
  install:
    - method: pip
      path: .


sphinx:
  fail_on_warning: true

formats:
  - pdf
