{% set name = "quickBayes" %}
{% set version = "1.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quickBayes-{{ version }}.tar.gz

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - numpy
    - scipy
    - joblib
    - gofit
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pip
    - numpy
  imports:
    - quickBayes
  commands:
    - pip check
    - python -m pytest .

about:
  home: https://github.com/mantidproject/quickBayes
  summary: 'quickBayes'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AnthonyLim23
