workflows.model_template: join('workflows', 'model_selection', 'model_template.py')
workflows.QlData: join('workflows', 'model_selection', 'qldata_main.py')
workflows.QSE: join('workflows', 'model_selection', 'qse_main.py')
workflows.MuonExpDecay: join('workflows', 'model_selection', 'muon_exp_decay_main.py')
